#ifndef AHRS_UIMAINSTATES_H
#define AHRS_UIMAINSTATES_H

enum class UIExternalComCode : uint8_t
{
    INIT_CONNECTION = 0x01,
    RECONNECTED = 0x02,
    REDUNDANT = 0x03,
    MASTER = 0x04,
    ERROR = 0x05,
    IDLE = 0x06
};

enum PagesType : uint8_t
{
    WELCOME_PAGE,
    SYSTEM_SETUP_PAGE,
    PLANE_SETTING_PAGE,
    CALLIBRATION_PAGE,
    RESTART_PAGE,
    EXIT_PAGE,
    AHRS_PAGE,
    LOGS_PAGE,
    MENU_PAGE,
    CONNECTING_PAGE,
    BITS_PAGE
};

#endif //AHRS_UIMAINSTATES_H
